- src/LtiGrade.php
- tests/LtiGradeTest.php
Canvas has a custom extension to send the submitted_at date of a grade so that submissions don't get marked as late in Canvas when they're sent past a due date.
See IMS Spec on extensions: http://www.imsglobal.org/spec/lti-ags/v2p0#extensions
I have tested these changes on a locally running version of PBQ and Canvas.
ETA: This param *should* be ignored when passing a grade to LMSes other than Canvas. I cannot test this locally however, and will need to wait to test it on dev.
> Add canvas extension to LtiGrade

- src/LtiServiceConnector.php
Adds a 60 second timeout to curl request using [CURLOPT_TIMEOUT](https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html)
There seems to be different timeout types for curl. For example 
1. [CURLOPT_CONNECTTIMEOUT](https://curl.se/libcurl/c/CURLOPT_CONNECTTIMEOUT.html): Number of seconds allotted for the request to connect to the server.
2. [CURLOPT_TIMEOUT](https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html): Number of seconds allotted for the entire request to finish. 
~I chose 1 because it seems like that's where we wanted the timeout to happen, but if it's not happy to make the change.~
Chose 2 cause that's what Guzzle uses. 
<details>
<summary>Test Pass:</summary>
</details>
> DEV-11264: Add timeout to LtiServiceConnector

- src/LtiDeepLinkResource.php
- tests/LtiDeepLinkResourceTest.php
The [LTI Deep Linking Specification](https://www.imsglobal.org/spec/lti-dl/v2p0#content-item-types) defines an optional parameter "text" for all core content item types. This "text" parameter is a plain description of the content item being defined, beyond title.
This PR adds support for this "text" parameter.
> Add 'text' parameter to Deep Link resources

- src/Interfaces/ILtiServiceConnector.php
- src/LtiServiceConnector.php
- tests/LtiServiceConnectorTest.php
Previously, when we tried to write a new lineitem and grade to an LMS with the makeServiceRequest, Guzzle was making the request which had the body as a string of JSON within quotes (`"{\"score\": 100}"`). This is because the Grade and LineItem __toString functions were encoding the body as JSON, and then we passed that into Guzzle in the `json` key, which then did a second `json_encode()`.
This PR fixes this by instead using the `body` key so the body data is passed as-is. I'm also making the arguments to this `makeServiceRequest()` method more clear to indicate the body is a string. Finally, I'm turning the headers array from Guzzle into a set of key-value pairs (by taking the first header), instead of each header key corresponding to an array of header values (`'header' => ['header …
> DATAINF-97 Change how POST requests are made to fix double-encoded JSON

- src/LtiAssignmentsGradesService.php
- src/LtiServiceConnector.php
AGS wasn't making use of the "next page" functionality, so I added that in. I also fixed the regex since when looking through the headers, the `Link` is actually the key and will never be found in the regex being checked against the value.
Lots of manual testing. Confirmed I could get all 42 assignments in a context. I also tested 0 and 1.
- [x ] I have run `composer test`
- [x ] I have run `composer lint-fix`
> DEV-11392: fix and add ability to get ALL lineItems in a container

- src/LtiAssignmentsGradesService.php
I was only able to test this locally on Canvas. In dev testing, I found that many requests do NOT include this in the headers. If we don't have it, we can just break the loop since we don't need to make any more paginated requests.
> DEV-11392: check to see if headers Link is set

- src/ImsStorage/ImsCache.php
- src/Interfaces/ICache.php
- src/LtiServiceConnector.php
- tests/Certification/Lti13CertificationTest.php
- tests/LtiServiceConnectorTest.php
This PR implements new functionality to clear the existing access token and retry the request if a 401 error occurs. If consecutive 401 errors occur, then the error is thrown.
I wrote new tests and manually updated the corresponding vendor file in `backend/app-api` with the updated code and performed gradebook syncs to confirm that:
1. If an invalid access token is provided on the first request, the request will retry.
2. If the access token is always invalid, the request retries only once before throwing an error.
Note that I added the following function to `Lti13Cache.php` (within the `app-api`) in accordance with the change to the interface:
```
public function clearAccessToken($key)
{
return Cache::forget($key);
}
```
> ONCALL-216: Implement invalid token retry.

- src/LtiServiceConnector.php
- tests/LtiServiceConnectorTest.php
Adding the status code to the body of the response payload because many LMSes do not include a status in the request headers. This is causing us to think many syncs failed, even if they were successful.
- [ x] I have run `composer test`
- [ x] I have run `composer lint-fix`
> DEV-11396: add status code to service request response

- composer.json
- src/Interfaces/ILtiServiceConnector.php
- src/Interfaces/IServiceRequest.php
- src/LtiAbstractService.php
- src/LtiAssignmentsGradesService.php
- src/LtiCourseGroupsService.php
- src/LtiNamesRolesProvisioningService.php
- src/LtiServiceConnector.php
- src/ServiceRequest.php
- tests/LtiAssignmentsGradesServiceTest.php
- tests/LtiCourseGroupsServiceTest.php
- tests/LtiNamesRolesProvisioningServiceTest.php
- tests/LtiServiceConnectorTest.php
Converts the LtiServiceConnector into a generic API client. Previously, each instance of the service connector was directly tied to a specific LtiRegistration, so it could only send grades to one LMS. This PR shifts the coupling of the LtiRegistration to the instance of the specific service (AssignmentGradesService, NamesRolesProvisioningService). So rather than having an API client that is tied directly to a single LMS that then is used by the GradesService, we now have a generic API client that various services tied to specific LMSes can all use.
Here's how we used to do things when syncing grades for two different LMSes:
```php
$registrationForLms1 = $this->ltiRepository->findRegistrationByIssuer($issuer->issuer, $issuer->client_id);
$registrationForLms2 = …
```
> MGMT-29 Make the LTI Service Connector into a generic API client

- src/LtiMessageLaunch.php
- tests/LtiMessageLaunchTest.php
We inadvertently broke somethings on our v3 beta branch and didn't know because we're not currently using them on the platform. Since a launch is the most fundamental part of LTI, I figured we should probably add some automated tests to it to make sure things don't break again.
> MGMT-32 Add automated tests for the LtiMessageLaunch

- src/LtiLineitem.php
- tests/LtiLineitemTest.php
Resource link id was not being sent in requests to create a line item. You can see that this field is documented here:
https://www.imsglobal.org/spec/lti-ags/v2p0#resourcelinkid-and-binding-a-line-item-to-a-resource-link
https://canvas.instructure.com/doc/api/line_items.html
Manual testing in Canvas LMS
> Include resourceLinkId attribute when creating line item

- src/LtiAbstractService.php
- src/LtiAssignmentsGradesService.php
- src/LtiServiceConnector.php
I couldn't get getLineItems() to return any data, and findOrCreateLineItem() was creating new line items constantly. It looks like the line items are actually returned into $response['body'] and not $response['body']['lineitems'], and this is backed up by the original PHP library and the Python library in these files:
https://github.com/IMSGlobal/lti-1-3-php-library/blob/master/src/lti/LTI_Assignments_Grades_Service.php
https://github.com/dmitry-viskov/pylti1.3/blob/master/pylti1p3/assignments_grades.py
Additionally, the 'tag' key was not being isset() tested like the other fields in findOrCreateLineitem() and so was producing a warning in PHP logs if the tag was not set in a returned line item.
Manual testing that shows the line items are now being returned from Canvas LMS.
I am …
> Fix fetching of line items and eliminate a PHP warning for missing key

- CHANGELOG.md
- UPGRADES.md
- src/Interfaces/ILtiServiceConnector.php
- src/LtiMessageLaunch.php
- src/LtiServiceConnector.php
- src/ServiceRequest.php
- tests/Certification/Lti13CertificationTest.php
- tests/LtiMessageLaunchTest.php
- tests/LtiServiceConnectorTest.php
Rather than using `file_get_contents()` to fetch the keyset, use the HTTP client provided in the service provider.
I created a branch on our platform which uses these changes and verified the E2E tests pass.
> PODB-266 Get the public keyset via a client instead of file_get_contents

- src/ImsStorage/ImsCache.php
Because the cacheLaunchData() and cacheNonce() methods do not load the cache prior to setting it, it effectively wipes out the cache each load. I think this would likely cause problems for applications where more than one user could be accessing the application at once. I have implemented my own cache, but thought I would fix this for others and to make sure I am understanding it right. We don't want it to wipe the entire cache each load, right? I think the launch data may be useful for a future request as the key is passed around. Since the default storage is in a system temp file, it will get wiped eventually by the system.
Furthermore, is there a reason $this was being returned in the functions that set cache values? I looked through the code and it isn't chained anywhere, nor is the …
> Default cache storage no longer wiping all but the latest nonce and launch body

- src/LtiDeepLink.php
Resolves a PHP warning that was noted in issue https://github.com/packbackbooks/lti-1-3-php-library/issues/43
Per specs at https://www.imsglobal.org/spec/lti-dl/v2p0/#deep-linking-settings the 'data' property of deep link settings is optional. In the scenario where this field was not sent by the platform (tested on Canvas) a PHP warning would be thrown:
`PHP message: PHP Notice: Undefined index: data in /.../vendor/packbackbooks/lti-1p3-tool/src/LtiDeepLink.php on line 33`
This change ensures that the 'data' property in the deep link response is only returned if it was sent by the platform.
Tested manually on Canvas
> Fix a PHP warning when optional 'data' property of deep link settings is not present in message launch.

- composer.json
Added the `"license": "Apache-2.0",` line to the `composer.json` file so it will no longer be flagged for not having a license by our linter.
@dbhynds
> SEC-64 Add Apache license to composer

- src/LtiMessageLaunch.php
Ensures that an JWK alg is set. Technically this property is optional and D2L doesn't include it currently. If someone's app is using `"firebase/php-jwt": "^6.0"` in their `composer.lock`, D2L launches would fail. (For the PR reviewer, currently we're using `^5.2` in our app, which is why the recent change didn't break D2L launches. It only affects `^6.0`.)
See this conversation for more details: https://github.com/packbackbooks/lti-1-3-php-library/issues/50. Thanks to snake for raising this issue.
^^^ No, but I manually tested it. Here's a pipeline where LTI tests pass using 6.0: https://gitlab.com/packback/questions/-/pipelines/517060983. There are some other failing tests, because I had to remove the google classroom library (which requires 5.2) to get our app to use 6.0. This is …
> MGMT-61 Fix key alg

- src/LtiServiceConnector.php
- tests/LtiServiceConnectorTest.php
Previously, when debugging mode was enabled, we only logged service requests. When it came to getting an access token, we called `$this->client->post()` which meant the request was never logged.
This implements a change such that all requests get funneled through `makeRequest()` which also handles logging the responses of those requests. This should enable debug logging if auth requests fail.
Still need to manually test.
> PODB-520 Improve logging on the LtiServiceConnector

- src/LtiServiceConnector.php
- src/ServiceRequest.php
In order to pass LMSes the same data we did previously we have changed the way we are forming the payload for our auth requests. This should fix the issues we are seeing with launching D2L and Blackboard instances. 
We have manually verified that the headers on the request now match what they previously were, and have tested the changes in the development environment.
> ONCALL-391 Fix LTI Header

- src/Enums/RequestTypes.php
- src/Interfaces/ILtiServiceConnector.php
- src/LtiAbstractService.php
- src/LtiAssignmentsGradesService.php
- src/LtiMessageLaunch.php
- src/LtiServiceConnector.php
- src/ServiceRequest.php
- tests/Certification/Lti13CertificationTest.php
This PR adds `LtiAssignmentsGradesService::updateLineitem()` and updates the `LtiServiceConnector` to handle `PUT` requests. It also updates the `ServiceRequest` class to add `Content-Type` to `PUT` and `POST` requests.
I applied the changes in this branch to my local environment (see [PR #6521](https://github.com/packbackbooks/questions/pull/6521) in the `questions` repo) and verified that, when updating posting requirements with GBS frequency set to `auto`, lineitems in Canvas updated as expected.
> PODB-563: Add functions for updating line items

- src/Interfaces/ILtiServiceConnector.php
- src/Interfaces/IServiceRequest.php
- src/LtiAbstractService.php
- src/LtiAssignmentsGradesService.php
- src/LtiCourseGroupsService.php
- src/LtiMessageLaunch.php
- src/LtiNamesRolesProvisioningService.php
- src/LtiServiceConnector.php
- src/ServiceRequest.php
- tests/LtiServiceConnectorTest.php
This PR moves the request type and method constants to the `ServiceRequest` object instead of the `LtiServiceConnector`. I think it makes more sense for them to live here, since they're describing the request itself, not anything about the connector.
This also fixes a bug where we were treating every request like an auth request in the logs.
Here's the branch: https://github.com/packbackbooks/questions/pull/6533
> PODB-563 Move type and method constants to ServiceRequest

- src/LtiMessageLaunch.php
- tests/LtiMessageLaunchTest.php
This PR updates how we generate the error message for a missing registration, adding the issuer URL and client ID to the message as per [the Jira ticket](https://packback.atlassian.net/browse/PODB-603).
I manually verified that the error message has the issuer URL and client ID appropriately substituted in the message:
<details><summary>Screenshot</summary>
Note: I got this error to throw by commenting out the `if ()` logic surrounding the exception.
</details>
> PODB-603: Update error message for missing registration

- src/LtiDeepLinkResource.php
- tests/LtiDeepLinkResourceTest.php
The current default value for $custom_params would be serialized into an array, which would make the request uncompliant to the specification and can lead to issues because the platform expects an object. Casting a null object will instead be serialized into an empty object which it is supposed to be.
I haven't done any automatic testing but setting $custom_params to this value using setCustomParams fixed the issue for us and if you don't trust us you can manually test the behavior by simple evaluating `json_encode((object) null) === '{}'`
> Fix invalid request when specifying no custom params

- src/LtiOidcLogin.php
- tests/LtiOidcLoginTest.php
This PR replaces the error string "Could not find registration details" with the `LtiMessageLaunch::getMissingRegistrationErrorMsg()` function. This was meant to be implemented in #63, but I missed it due to the two original error strings being different.
I copy+pasted the code in my local BE, forced the exception to always be thrown, and verified that the message appears when attempting to log in via an LTI 1.3 launch.
<details><summary>Screenshot</summary>
</details>
> PODB-612: Replace registration error with dynamic function.

- src/LtiDeepLinkResource.php
- src/LtiDeepLinkResourceIcon.php
- tests/LtiDeepLinkResourceIconTest.php
- tests/LtiDeepLinkResourceTest.php
The LtiDeepLinkResource was missing the url and thumbnail properties as described [inside the deep linking specification](https://www.imsglobal.org/spec/lti-dl/v2p0#deep-linking-response-example). This PR adds those properties and some more php-docs.
I added tests for both the new class and the new properties
> Add icon to deep link resource

- .github/workflows/run_tests.yml
This adds testing for our minimum php version (7.4) and the latest. This ensures we don't break something by adding php8-specific syntax.
> Use a matrix to test php versions

- src/Interfaces/ILtiRegistration.php
- src/Interfaces/IMessageValidator.php
- src/Interfaces/IServiceRequest.php
Per the feedback in https://github.com/packbackbooks/lti-1-3-php-library/issues/77, I've marked internal interfaces as such so that people don't try to implement them themselves. As the issue author indicated, there was no indication that these interfaces are only for internal use and shouldn't be used externally.
> Mark internal interfaces as such

- src/LtiGrade.php
PHP 8.2 will deprecate dynamic properties, so to avoid it, I added a class property.
I'm using PHPStan to scan all classes with a warning "Access to an undefined property..." after I added the missing property in the class, the warning is gone.
> Fixed dynamic properties deprecation in PHP 8.2

- src/LtiOidcLogin.php
This allows login to function in applications which override the default value of PHP's arg_separator.output.
In these usages of http_build_query, we always want '&', otherwise the query breaks. For applications that use code like:
`ini_set('arg_separator.output', '&amp;');`
elsewhere, this will cause issues.
> Use default arg separator for http_build_query in login

- CHANGELOG.md
- src/LtiAssignmentsGradesService.php
- src/ServiceRequest.php
- tests/LtiAssignmentsGradesServiceTest.php
This PR adds a `AssignmentGradesService::deleteLineItem` method to be used by LTI tools trying to proactively manage LMS columns.
This PR has been tested manually in related feature-work by deleting a line item via the new method on a local developer instance of Canvas. See https://github.com/packbackbooks/questions/pull/7933.
> PODC-414: Add a "Delete Lineitem" Method

- src/LtiAbstractService.php
- src/LtiAssignmentsGradesService.php
- tests/LtiAssignmentsGradesServiceTest.php
This PR adds a method for validating that a service request has valid scopes. It also adds two missing scopes to the AGS, which was highlighted in https://github.com/packbackbooks/lti-1-3-php-library/pull/85.
> Validate scopes before a request

- CHANGELOG.md
- src/LtiAssignmentsGradesService.php
This PR fixes the URL for updating an individual line item.
I manually verified that these changes allow line items to be updated in Canvas.
> PODA-966: Fix updating a line item

- CHANGELOG.md
The URL for the PR in the changelog was incorrect; rather than double-checking after creating the PR, I wrongly assumed that there wouldn't be any other PRs since the last one released.
> PODA-966: Fix changelog URL

- src/LtiMessageLaunch.php
- tests/Certification/Lti13CertificationTest.php
This PR adds a different error messages to differentiate between failing to find a public key (when the request to get the key set fails) vs when there isn't a public key matching the JWT. This is to clarify exactly what is causing the error `Unable to find public key.`, which was previously being thrown in two places.
I copy+pasted my changes to the backend vendor code and verified that, by forcing that exception to be thrown, the error is displayed as expected. I also verified that debugging can be toggled on the service connector by passing `true` in for the last parameter.
> ONCALL-718: Differentiate error messaging for public key

- src/LtiMessageLaunch.php
Hi there. I represent GoReact, a large educational feedback tool. We are adding support for LTI 1.3 and have decided to use your library to help us. In implementing this, we want to make a few modifications that will help us with the validation phases, but unfortunately, all the validation methods in the `LtiMessageLaunch` class are private and therefore cannot be modified by a class that extends it. This change simply makes those private methods protected so an extending class can modify them. We would love to work with you guys and potentially even help support this library if you feel you need extra help. LTI is an important part of what we do so we will be actively interested in the success of this project.
- [ x] I ran `composer test` before opening this PR
- [ x] I ran `composer …
> Allow LtiMessgageLaunch validation steps to be modified by tool providers

- src/LtiGrade.php
It seems if you blindly attach extra metadata onto GBS requests, some LMS will bomb out during request validation. Since keeping track of the LMS type (i.e. determining when to include metadata) is an application-level concern, I'm just making note of a pitfall on the relevant function.
_(Documentation-only change)_
> PODC-859: Add a Disclaimer to `LtiGrade::setCanvasExtension`

- src/LtiLineitem.php
- tests/LtiLineitemTest.php
"gradesReleased" is a new feature of the [Assignment and Grade Services 2.0](https://www.imsglobal.org/spec/lti-ags/v2p0#gradesreleased) as of January 24th, 2023. This just adds the property to the line item model so that it may be retreived/set
> Add gradesReleased to LtiLineItem

- src/LtiOidcLogin.php
As per RFC6749, section 3.1, the auth URL may have a query string. E.g. 'https://example.com/oidc?auth'. So, don't assume that '?' will be the separator when generating the auth URL.
This change ensures that LtiOidcLogin::doOidcLoginRedirect() creates the auth URL properly in cases where the platform's auth URL contains a query component, and where '?' will already be present in the URL.
Prior to this change, an auth URL like 'https://example.com/oidc?auth' would result in the code generating something like:
'https://example.com/odic?auth?other=1&params=2&here=3' (note the 2x '?').
I've tested this one manually by adding some query params to the saved auth URL for a test platform and performing a launch. Without the change, there's a problem finding the scope because of the query params …
> Fix bug with authorization URLs having a query component

- src/LtiDeepLinkResourceIframe.php
- tests/LtiDeepLinkResourceIframeTest.php
Discussed in #108, Canvas expects a `src` parameter on iframe deeplink resources. Even if the URL of the deeplink is set, nothing will be rendered if `src` is not present. This PR adds the `src` parameter to the existing `height` and `width` values. 
Tests were added. I also ran this in a dev instance against Canvas to verify the functionality is behaving as expected.
> Add src field to iframe resource

- src/LtiServiceConnector.php
- src/ServiceRequest.php
- tests/LtiServiceConnectorTest.php
> Add the ability to mask log data

- src/LtiServiceConnector.php
- tests/LtiServiceConnectorTest.php
Currently when we log requests, it's spits out a nasty multi-line logs for the response object that are impossible to read in stackdriver. Example:
```
[28-Nov-2023 15:13:42 UTC] Getting lineitems: Array
(
[request_method] => GET
[request_url] => https://canvas.localhost/api/lti/courses/13/line_items
[response_headers] => Array
(
[Server] => nginx/1.25.2
[Date] => Tue, 28 Nov 2023 15:13:42 GMT
[Content-Type] => application/vnd.ims.lis.v2.lineitemcontainer+json; charset=utf-8
[Transfer-Encoding] => chunked
[Connection] => keep-alive
[Status] => 200 OK
[X-Request-Cost] => 0.06348237000029755
[Cache-Control] => max-age=0, private, must-revalidate
[X-Request-Context-Id] => 0ba25001-7296-4114-985d-12ced8ef7d53
[Strict-Transport-Security] => max-age=31536000
[Referrer-Policy] => …
```
> Json encode log objects instead of printing a multiline string

- src/Interfaces/ILtiServiceConnector.php
- tests/DeepLinkResources/ResourceTest.php
- tests/Lti1p1KeyTest.php
- tests/LtiAssignmentsGradesServiceTest.php
- tests/LtiCourseGroupsServiceTest.php
- tests/LtiDeploymentTest.php
- tests/LtiGradeSubmissionReviewTest.php
- tests/LtiMessageLaunchTest.php
- tests/ServiceRequestTest.php
Gets us to like 99% code coverage. Also, testing found a legit bug FTW!
> Improve code coverage

- src/LtiServiceConnector.php
- tests/LtiServiceConnectorTest.php
Code Climate flagged this up, and I saw some opportunities to simplify it.
> Reduce complexity in LtiServiceConnector::getAll()

- UPGRADES.md
Just minor fixes to the upgrade wording, noticed during upgrading to v.6.0.0.
- typo
- including the LtiDeployment class in the list of classes with changed method signatures, since clients will definitely be using that.
Just docs, no testing required.
> fix typo and missed class

- composer.json
- tests/LtiOidcLoginTest.php
This popped up a few days ago. Gets tests back in a passing state.
> Fix linting error

- .github/workflows/run_tests.yml
- composer.json
The recently released version 6 contains changes that are only available since PHP 8.1, like initializing class variables in the constructor (see [this RFC](https://wiki.php.net/rfc/new_in_initializers) ). The code example below is from **LtiMessageLaunch**:
````
public function __construct(
private IDatabase $db,
private ICache $cache,
private ICookie $cookie,
private ILtiServiceConnector $serviceConnector
) {
$this->launch_id = uniqid('lti1p3_launch_', true);
}
````
Having a php version designated in the `composer.json` throws an error if someone with an out-of-date php version attempts to require the package, providing an early warning that they wouldn't be able to use it due to the newer language constructs implemented.
> Add PHP version requirement to composer.json

- src/LtiMessageLaunch.php
When throwing an `LtiException` inside a try-catch, pass along the previous exception with it.
This is in response to https://github.com/packbackbooks/lti-1-3-php-library/issues/145
Here are these changes in our platform: https://gitlab.com/packback/questions/-/pipelines/1380815824
> Pass the previous exception

- src/DeepLinkResources/DateTimeInterval.php
- src/DeepLinkResources/Iframe.php
- src/DeepLinkResources/Resource.php
- src/DeepLinkResources/Window.php
- src/LtiGrade.php
- src/LtiGradeSubmissionReview.php
- src/LtiMessageLaunch.php
- tests/Certification/Lti13CertificationTest.php
- tests/DeepLinkResources/ResourceTest.php
- tests/JwksEndpointTest.php
- tests/Lti1p1KeyTest.php
- tests/LtiAssignmentsGradesServiceTest.php
- tests/LtiGradeSubmissionReviewTest.php
- tests/LtiGradeTest.php
- tests/LtiLineitemTest.php
- tests/LtiRegistrationTest.php
Fixed all coding style complaints raised by laravel/pint against current head 83ad0be
Fixed unit test after confirming public key string calculated by phpseclib3 is correct against python's cryptography library.
Did not fix coverage tests as I don't have a CC secret, but pcov is locally satisfied.
No functional changes, just prepping to address issue 149.
> Fixed lint and unit test issues.

- src/LtiConstants.php
ROLE_SCOPE_MENTOR constant is missing a '.'
> fix role scope mentor claim

- src/DeepLinkResources/Resource.php
- tests/DeepLinkResources/ResourceTest.php
This field isn't valid per 1edtech cert specs (lol... at least that's what they say). Tests still pass.
> ENG-4213: remove the iframe target from DL resource

- .gitignore
- CLAUDE.md
- src/LtiAssignmentsGradesService.php
- tests/LtiAssignmentsGradesServiceTest.php
See: https://github.com/packbackbooks/lti-1-3-php-library/issues/159
> Add user ID filter to grades

- src/DeepLinkResources/DateTimeInterval.php
- tests/DeepLinkResources/DateTimeIntervalTest.php
- tests/DeepLinkResources/ResourceTest.php
From the spec ResourceLink.(available/submission).(startDateTime/endDateTime) are both optional fields and do not need to both be present for the Resource Link to work.
https://www.imsglobal.org/spec/lti-dl/v2p0#lti-resource-link
<details>
<summary>`composer test` results</summary>
</details>
<details>
<summary>`composer lint-fix` results</summary>
</details>
> ENG-4471: Allow DateTimeInterval to have `null` start and end
